### ISSUE TITLE
All programs compiled with OWCCv1.9 are detected as viruses

### ISSUE THREAD

**Issue by denis-shienkov** [open-watcom/open-watcom-1.9#1]
E.g. on my Windows 10 it is detected as CRITICAL:

```
Backdoor:Win32/CobaltStrikeLoader.B!dha

This program provides remote access to the computer on which it is installed. 
```

**Comment by jmalak** [comment]
Anyway OW is build on Azure Pipeline from source on build machine image handled by Microsoft.
I am 99.999% sure that it is problem of antivirus software.
It is ignorance of suppliers of antivirus software to fix such issues.
Or it can be the computer where you compile be infected, but in this case you should get warning for other files not created by OW.

**Comment by jmalak** [comment]
What antivirus SW you are using?
